[package]
name = "pacing_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.8.0"
heck = "0.4.0"
serde = { version = "1.0.152", features = ["derive"] }
